var GAME_LEVELS = [
  [
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                    xxxxx       ",
   "                          o                                         xx!xx       ",
   "                                                                    xx!xx       ",
   "                          x                                           v         ",
   "                      o       o                                                 ",
   "                                                                                ",
   "                     xxx     xxx                                             o  ",
   "                                                                           xxxxx",
   "                                       o  o  o  o                          xxxxx",
   "    @                                                                      xxxxx",
   "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "         x!!!x                                                                  ",
   "         x!!!x                                                                  ",
   "         xxxxx                                                                  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
  ],
  [
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                                ",
   "                                          o o                                   ",
   "                        o                                                       ",
   "                                         xxxxx                             o    ",
   "             xxxx       o       o                                               ",
   "     @       x  x                                                xxxxx          ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "
  ],
];
